package org.pgist.wfengine.web;

import java.util.ArrayList;
import java.util.Collection;
import java.util.LinkedHashMap;
import java.util.HashMap;
import java.util.Iterator;
import java.util.List;
import java.util.Map;
import java.util.Set;

import javax.servlet.http.HttpServletRequest;

import org.directwebremoting.WebContextFactory;
import org.pgist.wfengine.Activity;
import org.pgist.wfengine.OpenWorkflow;
import org.pgist.wfengine.RunningContext;
import org.pgist.wfengine.Workflow;
import org.pgist.wfengine.WorkflowEngine;
import org.pgist.wfengine.WorkflowAgendaItem;
import org.pgist.wfengine.activity.GroupActivity;
import org.pgist.wfengine.activity.MeetingActivity;
import org.pgist.wfengine.activity.PGameActivity;
import org.pgist.wfengine.activity.PManualGameActivity;
import org.pgist.wfengine.activity.PMethodActivity;
import org.pgist.wfengine.activity.SituationActivity;
import org.pgist.wfengine.util.Utils;



/**
 * DWR Agent class for Workflow Management.
 * 
 * @author kenny
 */
public class WorkflowAgent {
    
    
    private WorkflowEngine engine;
    
    
    public void setEngine(WorkflowEngine engine) {
        this.engine = engine;
    }
    
    
    /*
     * ------------------------------------------------------------------------
     */
    
    
    /**
     * Get template list. In LitEngine, a template is actually an instance of SituationActivity.
     * 
     * @return A map contains:
     *     <ul>
     *         <li>successful - boolean, whether the operation succeed</li>
     *         <li>reason - string, the reason why it fails</li>
     *         <li>
     *           html - string, html source segment generated by "/WEB-INF/jsp/workflow/wf_templates.jsp". In this page the following variables are avaiable:<br>
     *             <ul>
     *               <li>tempaltes - a list of SituationActivity objects</li>
     *             </ul>
     *         </li>
     *     </ul>
     */
    public Map getTemplates(HttpServletRequest request) {
        Map results = new HashMap();
        results.put("successful", false);
        
        try {
            /*
             * Get all the templates
             */
            Collection<SituationActivity> templates = engine.getTemplateSituations();
            
            request.setAttribute("templates", templates);
            
            results.put("html", WebContextFactory.get().forwardToString("/WEB-INF/jsp/workflow/wf_templates.jsp"));
            
            results.put("successful", true);
        } catch (Exception e) {
            e.printStackTrace();
            results.put("reason", e.getMessage());
        }
        
        return results;
    }//getTemplates()
    
    
    /**
     * Create a workflow instance from the given template.
     * 
     * @param params A map contains:
     *     <ul>
     *         <li>situationId - int, id of a SituationActivity object</li>
     *         <li>name, string, name of this situation</li>
     *         <li>description, string, description of this situation</li>
     *     </ul>
     * 
     * @return A map contains:
     *     <ul>
     *         <li>successful - boolean, whether the operation succeed</li>
     *         <li>reason - string, the reason why it fails</li>
     *         <li>workflowId - int, id of the newly created Workflow object</li>
     *     </ul>
     */
    public Map createInstance(Map params) {
        Map results = new HashMap();
        results.put("successful", false);
        
        try {
            Long situationId = new Long((String) params.get("situationId"));
            
            String name = (String) params.get("name");
            String description = (String) params.get("description");
            if (name==null || description==null) {
                results.put("reason", "name or description is missing.");
            }
            
            Workflow workflow = engine.createWorkflow(situationId, name, description);
            
            results.put("workflowId", workflow.getId());
            results.put("successful", true);
        } catch (Exception e) {
            results.put("reason", e.getMessage());
            e.printStackTrace();
        }
        
        return results;
    }//createInstance()
    
    
    /**
     * Get situation list.
     * 
     * @param params A map contains:
     *     <ul>
     *         <li>type - string, type of workflows. ["running" | "all"]. Default is "all"</li>
     *     </ul>
     * 
     * @return A map contains:
     *     <ul>
     *         <li>successful - boolean, whether the operation succeed</li>
     *         <li>reason - string, the reason why it fails</li>
     *         <li>instanceTotal - total number of instances (runningWorkflows + finishedWorkflows)</li>
     *         <li>runningTotal - total number of running instances</li>
     *         <li>openRunningTotal - total number of running and open accessed instances</li>
     *         <li>openInstanceId - id of one open accessed instance, if there are many such instances, the id will be a random one.</li>
     *         <li>finishedTotal - total number of running instances</li>
     *         <li>instanceId - if runningTotal=1, this is the id of that instance</li>
     *         <li>
     *           html - string, html source segment generated by "/WEB-INF/jsp/workflow/wf_workflows.jsp". In this page the following variables are avaiable:<br>
     *             <ul>
     *               <li>runningWorkflows - a list of running Workflow objects</li>
     *               <li>finishedWorkflows - a list of finished Workflow objects</li>
     *               <li>newWorkflows - a list of new Workflow objects</li>
     *             </ul>
     *         </li>
     *     </ul>
     */
    public Map getWorkflows(Map params,HttpServletRequest request) {
        Map results = new HashMap();
        results.put("successful", false);
        
        try {
            Collection runningWorkflows = engine.getRunningWorkflows();
            request.setAttribute("runningWorkflows", runningWorkflows);
            results.put("runningTotal", runningWorkflows.size());
            int openRunningTotal = 0;
            long openInstanceId = -1;
            for (Workflow one : (Collection<Workflow>) runningWorkflows) {
                if (one.isOpenAccess()) {
                    openRunningTotal++;
                    openInstanceId = one.getId();
                }
            }
            results.put("openRunningTotal", openRunningTotal);
            results.put("openInstanceId", openInstanceId);
            request.setAttribute("openRunningTotal", openRunningTotal);
            request.setAttribute("openInstanceId", openInstanceId);
            
            Collection finishedWorkflows = engine.getFinishedWorkflows();
            request.setAttribute("finishedWorkflows", finishedWorkflows);
            results.put("instanceTotal", finishedWorkflows.size());
            request.setAttribute("instanceTotal", finishedWorkflows.size());
            
            if ("all".equalsIgnoreCase((String) params.get("type"))) {
                /*
                 * Get new workflows
                 */
                Collection newWorkflows = engine.getNewWorkflows();
                request.setAttribute("newWorkflows", newWorkflows);
            }
            
            int instanceTotal = runningWorkflows.size() + finishedWorkflows.size();
            results.put("instanceTotal", instanceTotal);
            
            if (runningWorkflows.size()==1) {
                Workflow workflow = (Workflow) runningWorkflows.iterator().next();
                results.put("instanceId", workflow.getId());
            }
            
            results.put("html", WebContextFactory.get().forwardToString("/WEB-INF/jsp/workflow/wf_workflows.jsp"));
            
            results.put("successful", true);
        } catch (Exception e) {
            e.printStackTrace();
            results.put("reason", e.getMessage());
        }
        
        return results;
    }//getWorkflows()
    
    /**
     * JSONP implementation: Get situation list.
     * 
     */
    public Map getOpenWorkflows() {
        Map results = new HashMap();
        results.put("successful", false);
        
        try {
            Collection runningWorkflows = engine.getRunningWorkflows();
            List openWorkflows = new ArrayList();
            
            int openRunningTotal = 0;
            for (Workflow one : (Collection<Workflow>) runningWorkflows) {
                if (one.isOpenAccess()) {
                    openRunningTotal++;
                    OpenWorkflow ow = new OpenWorkflow(one.getName(), one.getId());
                    openWorkflows.add(ow);         
                }
            }
            results.put("openWorkflows", openWorkflows);
            results.put("openRunningTotal", openRunningTotal);
         
            
            results.put("successful", true);
        } catch (Exception e) {
            e.printStackTrace();
            results.put("reason", e.getMessage());
        }
        
        return results;
    }//getWorkflows()
    
    
    /**
     * Start the given workflow instance.
     * 
     * @param params A map contains:
     *     <ul>
     *         <li>workflowId - int, id of a Workflow object</li>
     *     </ul>
     * 
     * @return A map contains:
     *     <ul>
     *         <li>successful - boolean, whether the operation succeed</li>
     *         <li>reason - string, the reason why it fails</li>
     *     </ul>
     */
    public Map startWorkflow(Map params) {
        Map results = new HashMap();
        results.put("successful", false);
        
        try {
            Long workflowId = new Long((String) params.get("workflowId"));
            
            engine.startWorkflow(workflowId);
            
            results.put("successful", true);
        } catch (Exception e) {
            e.printStackTrace();
            results.put("reason", e.getMessage());
        }
        
        return results;
    }//startWorkflow()
    
    
    /**
     * Get the entry page for the given workflow instance.
     * 
     * @param params A map contains:
     *     <ul>
     *         <li>workflowId - int, id of a Workflow object</li>
     *     </ul>
     * 
     * @return A map contains:
     *     <ul>
     *         <li>successful - boolean, whether the operation succeed</li>
     *         <li>reason - string, the reason why it fails</li>
     *         <li>
     *           html - string, html source segment generated by "/WEB-INF/jsp/workflow/wf_workflow.jsp". In this page the following variables are avaiable:<br>
     *             <ul>
     *               <li>workflows - a list of Workflow objects</li>
     *             </ul>
     *         </li>
     *     </ul>
     */
    public Map getWorkflow(Map params, HttpServletRequest request) {
        Map results = new HashMap();
        results.put("successful", false);
        
        try {
            Long workflowId = new Long((String) params.get("workflowId"));
            
            Workflow workflow = engine.getWorkflowById(workflowId);
            
            request.setAttribute("workflow", workflow);
            
            results.put("html", WebContextFactory.get().forwardToString("/WEB-INF/jsp/workflow/wf_workflow.jsp"));
            
            results.put("successful", true);
        } catch (Exception e) {
            e.printStackTrace();
            results.put("reason", e.getMessage());
        }
        
        return results;
    }//getWorkflow()
    
    /**
     * For SPT implementation, need to get workflow and iterate through steps (completed, active, future)
     * in code. In standalone web implementation this was done in ws_workflow.js with the help of taglibs and JavaScript.
     * @param workflow_id
     * @return Map of workflow steps
     */
    
    
    public List getWorkflow(Long workflowId){
    	List workflowSequence = new ArrayList();
        
        try {
            //Long workflowId = new Long((String) workflow_id);
            
            Workflow workflow = engine.getWorkflowById(workflowId);
            
            //Iterate workflow and create JSON object
            
           /* //Get finished steps workflow.situation.context.histories
           List <Activity> sHistory = workflow.getSituation().getContext().getHistories();
            
            for (Iterator sit=sHistory.iterator(); sit.hasNext(); ) {
                //Actually a MeetingActivity, but need to be more generic? 
            	//Need to call getContext rather than getRunningContext which abstract type Activity doesn't offer.
            	GroupActivity sone = (GroupActivity)Utils.narrow(sit.next());
                
                List <Activity> mHistory = sone.getContext().getHistories();
                for (Iterator mit=mHistory.iterator(); mit.hasNext(); ) {
                	//Actually a PMethodActivity
                	GroupActivity mone = (GroupActivity)Utils.narrow(mit.next());
                	workflowSequence.put("mHistoryActivity", mone);
                	
                	List <Activity> gHistory = mone.getContext().getHistories();
                	for (Iterator git=gHistory.iterator(); git.hasNext(); ) {
                    	PManualGameActivity gone = (PManualGameActivity) Utils.narrow(git.next());
                    	workflowSequence.put("gHistoryActivity", gone);
                    }
                }
                
            }*/
            
            Set <Activity> sActive = workflow.getSituation().getContext().getPendingActivities();
            for (Iterator sit=sActive.iterator(); sit.hasNext(); ) {
                GroupActivity sone = (GroupActivity) Utils.narrow(sit.next());
               
                Set <Activity> mActive = sone.getContext().getPendingActivities();
                for (Iterator mit=mActive.iterator(); mit.hasNext(); ) {
                	GroupActivity mone = (GroupActivity)Utils.narrow(mit.next());
                	WorkflowAgendaItem item = new WorkflowAgendaItem();
                	item.setWorkflowId(workflowId);
                	item.setType(mone.getType());
                	item.setStatus("active");
                	item.setDescription(mone.getDescription());
                	item.setContextId(mone.getContext().getId());
                	
                	List pgameActivityList = new ArrayList();
                	
                	List <Activity> gActiveHistoryActivities = mone.getContext().getHistories();
                	for (Iterator git=gActiveHistoryActivities.iterator(); git.hasNext(); ) {
                    	PManualGameActivity gone = (PManualGameActivity) Utils.narrow(git.next());
                    	WorkflowAgendaItem gameItem = new WorkflowAgendaItem();
                    	gameItem.setType(gone.getType());
                    	gameItem.setStatus("activehistory");
                    	gameItem.setTitle(gone.getTitle());
                    	gameItem.setContextId(mone.getContext().getId());
                    	gameItem.setActivityId(gone.getId());
                    	gameItem.setBeginTime(gone.getBeginTime());
                    	gameItem.setEndTime(gone.getEndTime());
                    	pgameActivityList.add(gameItem);
                    }
                	
                	Set <Activity> gActive = mone.getContext().getRunningActivities();
                	for (Iterator git=gActive.iterator(); git.hasNext(); ) {
                		PManualGameActivity gone = (PManualGameActivity) Utils.narrow(git.next());
                		WorkflowAgendaItem gameItem = new WorkflowAgendaItem();
                    	gameItem.setType(gone.getType());
                    	gameItem.setStatus("active");
                    	gameItem.setTitle(gone.getTitle());
                    	gameItem.setContextId(mone.getContext().getId());
                    	gameItem.setActivityId(gone.getId());
                    	gameItem.setBeginTime(gone.getBeginTime());
                    	gameItem.setEndTime(gone.getEndTime());
                    	pgameActivityList.add(gameItem);
                    }
                	
                	List <Activity> gActiveFuture = mone.getContext().getFutureActivities();
                	for (Iterator git=gActiveFuture.iterator(); git.hasNext(); ) {
                		PManualGameActivity gone = (PManualGameActivity) Utils.narrow(git.next());
                		WorkflowAgendaItem gameItem = new WorkflowAgendaItem();
                    	gameItem.setType(gone.getType());
                    	gameItem.setStatus("future");
                    	gameItem.setTitle(gone.getTitle());
                    	gameItem.setContextId(mone.getContext().getId());
                    	gameItem.setActivityId(gone.getId());
                    	gameItem.setBeginTime(gone.getBeginTime());
                    	gameItem.setEndTime(gone.getEndTime());
                    	pgameActivityList.add(gameItem);
                    }
                	
                	item.setPgameActivityList(pgameActivityList);
                	workflowSequence.add(item);
                }
            }
                
           /* List <Activity> sFuture = workflow.getSituation().getContext().getFutureActivities();
            for (Iterator sfit=sFuture.iterator(); sfit.hasNext(); ) {
            	MeetingActivity sfone = (MeetingActivity) Utils.narrow(sfit.next());

            	List <Activity> mFuture = sfone.getContext().getFutureActivities();
            	for (Iterator mit=mFuture.iterator(); mit.hasNext(); ) {
            		PMethodActivity mone = (PMethodActivity) Utils.narrow(mit.next());
            		workflowSequence.put("mFuture", mone);

            		List <Activity> gFuture = mone.getContext().getFutureActivities();
            		for (Iterator git=gFuture.iterator(); git.hasNext(); ) {
            			PManualGameActivity gone = (PManualGameActivity) Utils.narrow(git.next());
            			workflowSequence.put("gFuture", gone);
            		}
            	}

            } */
            
           
        } catch (Exception e) {
            e.printStackTrace();
        }
        
        return workflowSequence;
    }//getWorkflow()
    
    
    /**
     * Execute the workflow to go over one specific activity.
     * 
     * @param params A map contains:
     *     <ul>
     *         <li>workflowId - int, id of a Workflow object</li>
     *         <li>contextId - int, id of a RunningContext object</li>
     *         <li>activityId - int, id of an Activity object</li>
     *         <li>nextId - int, id of an Activity object. (Required for some activities.)</li>
     *     </ul>
     * 
     * @return A map contains:
     *     <ul>
     *         <li>successful - boolean, whether the operation succeed</li>
     *         <li>reason - string, the reason why it fails</li>
     *     </ul>
     */
    public Map nextStep(Map params) {
        Map results = new HashMap();
        results.put("successful", false);
        
        try {
            Long workflowId = new Long((String) params.get("workflowId"));
            Long contextId = new Long((String) params.get("contextId"));
            Long activityId = new Long((String) params.get("activityId"));
            
            String nextIdStr = (String) params.get("nextId");
            if (nextIdStr==null || nextIdStr.length()==0) {
                engine.executeWorkflow(workflowId, contextId, activityId);
            } else {
                Long nextId = new Long((String) params.get("nextIdStr"));
                //engine.executeWorkflow(workflowId, contextId, activityId, nextId);
            }
            
            results.put("successful", true);
        } catch (Exception e) {
            e.printStackTrace();
            results.put("reason", e.getMessage());
        }
        
        return results;
    }//nextStep()
    
    
    /**
     * Set the open access status for one workflow instance.
     * 
     * @param params A map contains:
     *     <ul>
     *         <li>workflowId - int, id of a Workflow object</li>
     *         <li>openAccess - string, "true" | "false"</li>
     *     </ul>
     * 
     * @return A map contains:
     *     <ul>
     *         <li>successful - boolean, whether the operation succeed</li>
     *         <li>reason - string, the reason why it fails</li>
     *     </ul>
     */
    public Map setOpenAccess(Map params) {
        Map results = new HashMap();
        results.put("successful", false);
        
        try {
            Long workflowId = new Long((String) params.get("workflowId"));
            
            engine.setOpenAccess(workflowId, "true".equalsIgnoreCase((String) params.get("openAccess")));
            
            results.put("successful", true);
        } catch (Exception e) {
            e.printStackTrace();
            results.put("reason", e.getMessage());
        }
        
        return results;
    }//nextStep()
        
}//class WorkflowAgent
